version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:80"
    volumes:
      - /home/maunick/Documentos/ecommerce_caps/public:/var/www/html/public
      - /home/maunick/Documentos/ecommerce_caps/resources:/var/www/html/resources
      - /home/maunick/Documentos/ecommerce_caps/node_modules:/var/www/html/node_modules
      - /home/maunick/Documentos/ecommerce_caps:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_caps
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
